#!/bin/bash
# startup script starts all the services on the container required to
# run the outreach portal
# Usage of the Script 
# To use startup.sh, run the command
# ./scripts/startup.sh
# starts the Apache service
service apache2 start
if [ $? -ne 0 ]
then
echo "Failed to start apache server"
exit
fi
# starts the mysql service
server mysql start
if [ $? -ne 0 ]
then
echo "Failed to start mysql server"
exit
fi
